import { Download, ExternalLink, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import ScanStatus from './ScanStatus'
import { EmptyState, Field, Section, Table } from './DataSection'
import { arrayOrEmpty, formatDate, formatDuration, titleCase, valueOrNA } from '../utils/formatters'
import { reportUrl } from '../services/api'

const pick = (object, ...keys) => keys.map((key) => object?.[key]).find((value) => value !== undefined && value !== null)
const asRecords = (value) => Array.isArray(value) ? value : []

function Overview({ scan }) {
  const overview = scan.overview || scan.summary || {}
  const cards = [['Subdomains discovered', pick(overview, 'subdomains_discovered', 'subdomainsCount', 'subdomains_count')], ['API endpoints discovered', pick(overview, 'api_endpoints_discovered', 'apiEndpointsCount', 'api_endpoints_count')], ['DNS records', pick(overview, 'dns_records', 'dnsRecordsCount', 'dns_records_count')], ['Cookies observed', pick(overview, 'cookies_observed', 'cookiesCount', 'cookies_count')], ['Security findings', pick(overview, 'security_findings', 'findingsCount', 'findings_count')], ['TLS status', pick(overview, 'tls_status', 'tlsStatus')]]
  return <><div className="metric-grid">{cards.map(([label, value]) => <div className="metric" key={label}><span>{label}</span><strong>{valueOrNA(value)}</strong></div>)}</div><Section eyebrow="Scan context" title="Overview"><div className="field-grid"><Field label="Target domain" value={pick(scan, 'domain', 'target_domain')} /><Field label="Scan status" value={<ScanStatus status={scan.status} progress={scan.progress} />} /><Field label="Started" value={formatDate(pick(scan, 'started_at', 'start_time', 'scan_start_time'))} /><Field label="Completed" value={formatDate(pick(scan, 'completed_at', 'completion_time', 'scan_completion_time'))} /><Field label="Duration" value={formatDuration(pick(scan, 'duration', 'scan_duration'), pick(scan, 'started_at', 'start_time'), pick(scan, 'completed_at', 'completion_time'))} /></div></Section></>
}

export default function Dashboard({ scan, onReset }) {
  const subdomains = asRecords(scan.subdomains?.subdomains || scan.subdomain_discovery || scan.subdomains)
  const endpoints = asRecords(scan.api_endpoints?.endpoints || scan.apiEndpoints || scan.endpoints)
  const dns = scan.dns?.records || scan.dns_records || scan.dns || {}
  const tls = scan.tls || scan.ssl || {}
  const http = scan.http || scan.http_recon || {}
  const headers = asRecords(scan.headers || scan.security_headers || scan.headers_security)
  const cookies = asRecords(scan.cookies || scan.cookie_security)
  const technologies = asRecords(scan.technologies || scan.technology_detection)
  const findings = asRecords(scan.findings || scan.security_findings)
  const errors = asRecords(scan.errors || scan.warnings)
  const robots = scan.robots || scan.robots_txt
  const sitemap = scan.sitemap || scan.sitemap_xml
  const scanId = pick(scan, 'scan_id', 'scanId', 'id')
  const httpsSecurity = scan.https_security || {}
  const posture = scan.security_posture || {}
  const surface = asRecords(scan.attack_surface)
  const timeline = asRecords(scan.timeline)
  const [selectedAsset, setSelectedAsset] = useState(surface[0])
  return <main className="content">
    <header className="topbar"><div><span className="eyebrow">Assessment workspace</span><h1>Reconnaissance overview</h1></div><button className="quiet-button" onClick={onReset}>New scan</button></header>
    <Overview scan={scan} />
    <Section eyebrow="HTTPS security" title="Transport posture"><div className="https-grid"><Field label="HTTPS availability" value={httpsSecurity.https_available} /><Field label="HTTP to HTTPS" value={httpsSecurity.http_to_https?.state} /><Field label="TLS version" value={httpsSecurity.tls_version} /><Field label="Certificate" value={httpsSecurity.certificate_status} /><Field label="Hostname match" value={httpsSecurity.hostname_match} /><Field label="Certificate expiry" value={formatDate(httpsSecurity.certificate_expiry)} /><Field label="HSTS" value={httpsSecurity.hsts?.present ? httpsSecurity.hsts.raw_value : 'NOT_OBSERVED'} /><Field label="Mixed content" value={`${asRecords(httpsSecurity.mixed_content).length} observed`} /><Field label="Secure cookies" value={httpsSecurity.secure_cookies} /></div></Section>
    <div className="two-col"><Section eyebrow="Security posture" title={`${valueOrNA(posture.score)} / ${valueOrNA(posture.max_score)}`}><div className="posture-reasons">{asRecords(posture.reasons).length ? posture.reasons.map((reason, index) => <div key={index}><span className={reason.applied ? 'rule-pass' : 'rule-neutral'}>{reason.applied ? `+${reason.points}` : '0'}</span><span>{valueOrNA(reason.rule)}</span><small>{valueOrNA(reason.evidence)}</small></div>) : <EmptyState>No posture rules returned.</EmptyState>}</div></Section><Section eyebrow="Attack surface" title={`${surface.length} observed assets`}><Table rows={surface} empty="No attack surface assets returned." columns={[{ key: 'type', label: 'Type' }, { key: 'value', label: 'Asset' }, { key: 'status', label: 'Status' }, { key: 'source', label: 'Source' }]} /></Section></div>
    <Section eyebrow="Recon graph" title="Observed asset relationships"><div className="recon-graph">{surface.length ? surface.map((asset) => <button className={`graph-node ${selectedAsset?.id === asset.id ? 'selected' : ''}`} key={asset.id} onClick={() => setSelectedAsset(asset)}><span>{asset.type}</span><strong>{asset.value}</strong></button>) : <EmptyState>No graph nodes returned.</EmptyState>}</div>{selectedAsset && <div className="asset-detail"><span className="eyebrow">Selected asset</span><Field label="Asset" value={selectedAsset.value} /><Field label="Source" value={selectedAsset.source} /><Field label="Evidence" value={selectedAsset.evidence} /></div>}</Section>
    <div className="two-col">
      <Section eyebrow="Discovery" title="Subdomains"><Table rows={subdomains} empty="No subdomains discovered." columns={[{ key: 'subdomain', label: 'Subdomain', render: (r) => r.subdomain || r.name }, { key: 'resolution', label: 'Resolution', render: (r) => r.resolved_ip || r.ip || r.resolution }, { key: 'http', label: 'HTTP', render: (r) => r.http_status || r.http }, { key: 'https', label: 'HTTPS', render: (r) => r.https_status || r.https }]} /></Section>
      <Section eyebrow="Discovery" title="API endpoints"><Table rows={endpoints} empty="No API endpoints discovered." columns={[{ key: 'endpoint', label: 'Endpoint', render: (r) => r.endpoint || r.url }, { key: 'method', label: 'Method' }, { key: 'source', label: 'Source' }, { key: 'status', label: 'Status' }]} /></Section>
    </div>
    <Section eyebrow="Infrastructure" title="DNS information"><div className="dns-grid">{['A', 'AAAA', 'CNAME', 'MX', 'NS', 'TXT'].map((type) => <div className="dns-card" key={type}><span>{type}</span>{asRecords(dns[type]).length ? asRecords(dns[type]).map((record, index) => <code key={index}>{valueOrNA(record)}</code>) : <small>No records found</small>}</div>)}</div></Section>
    <div className="two-col"><Section eyebrow="Transport security" title="TLS / SSL"><div className="field-grid"><Field label="Certificate status" value={tls.status || tls.certificate_status} /><Field label="Subject" value={tls.subject || tls.certificate_subject} /><Field label="Issuer" value={tls.issuer} /><Field label="Valid from" value={formatDate(tls.valid_from || tls.not_before)} /><Field label="Valid until" value={formatDate(tls.valid_until || tls.not_after)} /><Field label="Days remaining" value={tls.days_remaining} /><Field label="Hostname match" value={tls.hostname_match} /><Field label="TLS version" value={tls.tls_version} /></div></Section><Section eyebrow="Transport" title="HTTP recon"><div className="field-grid"><Field label="HTTP status" value={http.status_code || http.http_status || http.status} /><Field label="Final URL" value={http.final_url} /><Field label="Content-Type" value={http.content_type} /><Field label="Server" value={http.server} /><Field label="Response time" value={http.response_time} /><Field label="HTTPS available" value={http.https_available} /></div></Section></div>
    <Section eyebrow="Controls" title="Security headers"><Table rows={headers} empty="No security header data returned." columns={[{ key: 'header', label: 'Header', render: (r) => r.header || r.name }, { key: 'status', label: 'Status', render: (r) => r.status || r.classification || (r.present ? 'Present' : 'Not observed') }, { key: 'observed_value', label: 'Observed value', render: (r) => r.observed_value || r.value || 'Not observed' }, { key: 'severity', label: 'Severity' }, { key: 'recommendation', label: 'Recommendation' }]} /></Section>
    <div className="two-col"><Section eyebrow="Cookie telemetry" title="Observed cookies"><Table rows={cookies} empty="No cookies observed in the target response." columns={[{ key: 'name', label: 'Cookie', render: (r) => r.name || r.cookie }, { key: 'secure', label: 'Secure' }, { key: 'httponly', label: 'HttpOnly', render: (r) => r.httponly ?? r.http_only }, { key: 'samesite', label: 'SameSite' }, { key: 'domain', label: 'Domain' }, { key: 'path', label: 'Path' }, { key: 'expires', label: 'Expires' }, { key: 'max_age', label: 'Max-Age' }]} /></Section><Section eyebrow="Fingerprinting" title="Technology detection"><Table rows={technologies} empty="No technology evidence returned." columns={[{ key: 'technology', label: 'Technology', render: (r) => r.technology || r.name }, { key: 'category', label: 'Category' }, { key: 'evidence', label: 'Evidence' }, { key: 'confidence', label: 'Confidence' }]} /></Section></div>
    <div className="two-col"><Section eyebrow="Policy files" title="robots.txt">{robots ? <pre className="readable-content">{typeof robots === 'string' ? robots : JSON.stringify(robots, null, 2)}</pre> : <EmptyState>robots.txt not available</EmptyState>}</Section><Section eyebrow="Policy files" title="sitemap.xml">{sitemap ? <div className="url-list">{asRecords(sitemap.urls || sitemap).map((url, index) => <div key={index}><ExternalLink size={14} />{valueOrNA(url)}</div>)}</div> : <EmptyState>sitemap.xml not available</EmptyState>}</Section></div>
    <Section eyebrow="Security review" title="Findings"><div className="finding-list">{findings.length ? findings.map((finding, index) => <article className="finding" key={finding.id || index}><div className="finding-top"><span className={`severity severity-${String(finding.severity || '').toLowerCase()}`}>{titleCase(finding.severity)}</span><strong>{valueOrNA(finding.title)}</strong><span className="finding-id">{valueOrNA(finding.id)}</span></div><p>{valueOrNA(finding.description)}</p><div className="finding-meta"><Field label="Category" value={finding.category} /><Field label="Affected URL" value={finding.affected_url} /><Field label="Source module" value={finding.source_module} /><Field label="Recommendation" value={finding.recommendation} /></div>{finding.evidence && <pre className="evidence">{valueOrNA(finding.evidence)}</pre>}</article>) : <EmptyState>No security findings returned.</EmptyState>}</div></Section>
    <Section eyebrow="Operations" title="Errors & warnings"><Table rows={errors} empty="No errors or warnings returned." columns={[{ key: 'module', label: 'Module' }, { key: 'error', label: 'Error', render: (r) => r.error || r.message }, { key: 'reason', label: 'Reason' }, { key: 'timestamp', label: 'Timestamp', render: (r) => formatDate(r.timestamp) }]} /></Section>
    <Section eyebrow="Scan timeline" title="Recorded events"><Table rows={timeline} empty="No timeline events returned." columns={[{ key: 'timestamp', label: 'Timestamp', render: (r) => formatDate(r.timestamp) }, { key: 'module', label: 'Module' }, { key: 'status', label: 'Status' }, { key: 'error', label: 'Error' }]} /></Section>
    {scanId && <div className="report-bar"><div><ShieldCheck size={19} /><span>Reports are generated by the backend for this scan.</span></div><div className="report-actions"><a href={reportUrl(scanId, 'json')} download><Download size={16} /> JSON report</a><a href={reportUrl(scanId, 'html')} download><Download size={16} /> HTML report</a></div></div>}
  </main>
}
