from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["dashboard"])

DASHBOARD = """<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Mini Pentest Framework</title><style>
:root{font-family:system-ui,sans-serif;color:#e7edf2;background:#090c10;--panel:#11171e;--line:#26303a;--muted:#83909d;--mint:#76f2bd;--red:#ff7480;--amber:#ffc268}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#123126,transparent 32%),#090c10}.wrap{max-width:1400px;margin:auto;padding:32px 5vw}.brand{color:var(--mint);font-weight:800;letter-spacing:.14em;font-size:12px}.notice{margin:24px 0;padding:12px 15px;border:1px solid #3a594d;background:#102019;color:#b8d9ca;font-size:12px}.hero{display:flex;justify-content:space-between;gap:20px;align-items:end;margin:36px 0}.eyebrow{color:var(--muted);font:11px monospace;text-transform:uppercase;letter-spacing:.1em}h1{font-size:clamp(32px,5vw,64px);margin:10px 0 0;letter-spacing:-.04em}h1 span{color:var(--mint)}.status{font:12px monospace;color:var(--mint);border:1px solid #2d5748;padding:10px 13px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.panel{background:rgba(17,23,30,.9);border:1px solid var(--line);padding:20px;min-width:0}.wide{grid-column:1/-1}.panel h2{font-size:17px;margin:7px 0 18px}.fields{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.field label{display:block;color:var(--muted);font:10px monospace;text-transform:uppercase}.field strong{display:block;margin-top:7px;font-size:13px;word-break:break-word}.empty{color:var(--muted);font-size:12px;padding:14px 0}table{border-collapse:collapse;width:100%;min-width:600px} .scroll{overflow:auto}th,td{text-align:left;border-bottom:1px solid var(--line);padding:10px 8px;font-size:12px;vertical-align:top}th{color:var(--muted);font:10px monospace;text-transform:uppercase}.finding{border-top:1px solid var(--line);padding:16px 0}.finding:first-child{border-top:0;padding-top:0}.sev{color:var(--mint);font:10px monospace;border:1px solid #35604e;padding:4px 6px}.sev-high,.sev-critical{color:var(--red);border-color:#66313a}.sev-medium{color:var(--amber);border-color:#644d2c}pre{white-space:pre-wrap;word-break:break-word;max-height:260px;overflow:auto;background:#0b0f14;padding:14px;color:#b9c6ce;font:11px monospace}@media(max-width:800px){.hero{display:block}.status{display:inline-block;margin-top:20px}.grid{grid-template-columns:1fr}.fields{grid-template-columns:1fr 1fr}}@media(max-width:480px){.fields{grid-template-columns:1fr}}
 </style></head><body><div class='wrap'><div class='brand'>MINI PENTEST FRAMEWORK</div><div class='notice'>Only scan domains you own or have explicit authorization to test.</div><div class='hero'><div><div class='eyebrow'>Authorized web reconnaissance</div><h1>Exposure <span>surface.</span></h1><form id='scan-form'><input id='domain' placeholder='Enter target domain' autocomplete='url' required><button>START RECON</button></form><div id='target' class='eyebrow'></div></div><div id='status' class='status'>NO SCAN PERFORMED</div></div><div id='dashboard' class='grid'><section class='panel wide'><div class='empty'>Enter a domain to begin a real reconnaissance scan.</div></section></div></div><script>
const esc=v=>String(v??'Not Available').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));const val=v=>v===null||v===undefined||v===''?'N/A':esc(typeof v==='object'?JSON.stringify(v):v);const panel=(eyebrow,title,body,wide='')=>`<section class="panel ${wide}"><div class="eyebrow">${eyebrow}</div><h2>${title}</h2>${body}</section>`;const fields=o=>`<div class="fields">${Object.entries(o).map(([k,v])=>`<div class="field"><label>${esc(k.replaceAll('_',' '))}</label><strong>${val(v)}</strong></div>`).join('')}</div>`;const table=(rows,cols,empty)=>rows?.length?`<div class="scroll"><table><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${val(r[c[1]])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:`<div class="empty">${empty}</div>`;
document.querySelector('#scan-form').addEventListener('submit',async event=>{event.preventDefault();const input=document.querySelector('#domain');const button=event.target.querySelector('button');button.disabled=true;document.querySelector('#status').textContent='VALIDATING DOMAIN';try{const response=await fetch('/api/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain:input.value})});const accepted=await response.json();if(!response.ok)throw Error(accepted.detail?.message||accepted.detail||'Scan could not be started');document.querySelector('#target').textContent=accepted.domain||input.value;poll(accepted.scan_id)}catch(error){document.querySelector('#status').textContent=error.message;button.disabled=false}});
async function poll(id){const s=await fetch('/api/scan/'+id+'/status').then(r=>r.json());document.querySelector('#status').textContent=s.status;if(!['COMPLETED','PARTIAL','FAILED'].includes(s.status)){return setTimeout(()=>poll(id),1800)}const data=await fetch('/api/scan/'+id+'/results').then(r=>r.json());render(data,id);document.querySelector('#scan-form button').disabled=false}
function render(d,id){const r=d.results||{};document.querySelector('#dashboard').innerHTML=panel('Scan context','Overview',fields({target:d.domain,status:d.status,started_at:d.started_at,completed_at:d.completed_at}),'wide')+panel('DNS','Records',fields(r.dns?.records||{}))+panel('Transport','TLS',fields(r.tls||{}))+panel('Transport','HTTP',fields({status_code:r.http?.status_code,final_url:r.http?.final_url,content_type:r.http?.content_type,server:r.http?.server,response_time:r.http?.response_time,https_available:r.http?.https_available}))+panel('Discovery','Subdomains',table(r.subdomains?.subdomains,[['Hostname','subdomain'],['IPs','resolved_ips'],['HTTP','http_status'],['HTTPS','https_status']],'No subdomains discovered.'))+panel('Discovery','API endpoints',table(r.api_endpoints?.endpoints,[['URL','url'],['Method','method'],['Source','source'],['Evidence','evidence']],'No API endpoints discovered.'))+panel('Controls','Security headers',table(r.headers,[['Header','header'],['Status','classification'],['Value','value'],['Evidence','evidence']],'No Data Returned'),'wide')+panel('Session','Cookies',table(r.cookies,[['Name','name'],['Secure','secure'],['HttpOnly','httponly'],['SameSite','samesite'],['Domain','domain'],['Path','path']],'No cookies observed.'))+panel('Fingerprinting','Technologies',table(r.technologies,[['Technology','technology'],['Category','category'],['Evidence','evidence'],['Confidence','confidence']],'No Data Returned'))+panel('Policy','robots.txt',r.robots?`<pre>${val(r.robots.content||r.robots)}</pre>`:'<div class="empty">robots.txt not available</div>')+panel('Policy','sitemap.xml',r.sitemap?`<pre>${val(r.sitemap.urls)}</pre>`:'<div class="empty">sitemap.xml not available</div>')+panel('Security review','Findings',(d.findings||[]).length?d.findings.map(f=>`<article class='finding'><span class='sev sev-${String(f.severity).toLowerCase()}'>${val(f.severity)}</span><strong> ${val(f.title)}</strong><p>${val(f.description)}</p><pre>${val(f.evidence)}</pre></article>`).join(''):'<div class="empty">No security findings returned.</div>','wide')+panel('Operations','Errors',table(d.errors,[['Module','module'],['Error','error'],['Reason','reason'],['Timestamp','timestamp']],'No errors or warnings returned.'),'wide')+panel('Reports','Download',`<a href='/api/scan/${id}/report/json'>JSON report</a> &nbsp; <a href='/api/scan/${id}/report/html'>HTML report</a>`,'wide')}
</script></body></html>"""

@router.get("/", response_class=HTMLResponse)
def dashboard(): return HTMLResponse(DASHBOARD)
